### ISSUE TITLE
Node red crashing with new Kasa nodes

### ISSUE THREAD

**Issue by sean-pt** [caseyjhol/node-red-contrib-tplink#41]
Thanks for your work. Since upgrading to v1 (Kasa node) Node Red has been periodically crashing with this error:

24 Sep 07:42:09 - [red] Uncaught Exception:
24 Sep 07:42:09 - Error: Could not determine device from sysinfo
    at Client.getDeviceFromSysInfo (C:\Users\johnc\.node-red\node_modules\tplink-smarthome-api\lib\client.js:221:15)
    at process (C:\Users\johnc\.node-red\node_modules\tplink-smarthome-api\lib\client.js:445:31)
    at Client.createOrUpdateDeviceFromSysInfo (C:\Users\johnc\.node-red\node_modules\tplink-smarthome-api\lib\client.js:465:13)
    at Socket.<anonymous> (C:\Users\johnc\.node-red\node_modules\tplink-smarthome-api\lib\client.js:380:22)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage [as onmessage] (dgram.js:910:8)

Can you shed any light on this? As far as I can tell I have no old TP-Link bulb or plug nodes in any of my flows.

**Comment by hufftheweevil** [comment]
Sounds like the same issue as https://github.com/caseyjhol/node-red-contrib-tplink/issues/38

Do you perhaps have a Kasa Cam on your network?

**Comment by sean-pt** [comment]
Yes I have two Kasa Spot cams on the network. Unfortunately there is no way to control these devices other than by the Kasa app so I have no way of changing their parameters. I have a error catchall in the flow but that doesn't seem to trap the error.

In the interim I can put them on another subnet I suppose.

**Comment by hufftheweevil** [comment]
Yes, that's an option. Other option is to disable discovery by setting Connection Poll Interval to 0. I'll try to determine a better fix this weekend.

**Comment by hufftheweevil** [comment]
See https://github.com/caseyjhol/node-red-contrib-tplink/issues/38 for continued discussion.
