### ISSUE TITLE
TCP Socket Closed errors

### ISSUE THREAD

**Issue by jerbzz** [caseyjhol/node-red-contrib-tplink#46]
**Problem enconutered**
I'm using multiple kasa nodes (four, and then one in a subflow which appears 7 times)  at different points in my flow to control a single HS100. I have another HS100 and a HS110 on my network but they are not configured in any of the kasa nodes.

I'm getting repeated errors in the Node-RED debug panel immediately after deploying the flow (this is with kasa node debug turned on): 

`Error connecting to device 192.168.1.112: Error: TCP Socket Closed. segment:0 hadError:false`

The nodes do work - for a period of time measured in minutes or hours, and then stop working completely. Sending input does not result in the device responding and there is no output from the node. Redeploying just the node which is borked seems to get things moving again. I'm having a hard time troubleshooting whether just one node stops working or all of them do.

I have disabled polling on all but one of the nodes, which is set to 15000/10000. This hasn't seemed to make any difference - if anything, it's worse now.

Happy to share my flow if that would be helpful.

**OS:** Raspbian buster on Pi 3B+

**Comment by jerbzz** [comment]
I should add that throughout this, the Kasa app still seems to be able to do the business.

**Comment by rakgupta** [comment]
I am seeing this in my logs (where XXX.XX.X.XXX is the IP address of TPLink HS105) - everything seems to work (MacOS - High Sierra)

TCP XXX.XX.X.XXX:9999 Error: TCP Socket Closed. segment:0 hadError:false
    at Socket.<anonymous> (/Users/rakesh/.node-red/node_modules/tplink-smarthome-api/lib/network/tcp-socket.js:104:31)
    at Object.onceWrapper (events.js:284:20)
    at Socket.emit (events.js:196:13)
    at TCP.<anonymous> (net.js:586:12)
[Hubitat Plug] device.send() Error: TCP Socket Closed. segment:0 hadError:false
    at Socket.<anonymous> (/Users/rakesh/.node-red/node_modules/tplink-smarthome-api/lib/network/tcp-socket.js:104:31)
    at Object.onceWrapper (events.js:284:20)
    at Socket.emit (events.js:196:13)
    at TCP.<anonymous> (net.js:586:12)

**Comment by jerbzz** [comment]
I saw that on another issue you posted. 

The difference is, I think, that the node stops working for me.

**Comment by Botched1** [comment]
For the record, I see the same thing on 2 KP115 units when getting energy readings @ 10s. They just stop updating after after a few days. Reload the node (typically I check/unckeck debug logging in the node and reload) then it will work again for a few days.
